import fs from "node:fs/promises";
import path from "node:path";
import { DoctorChecker } from "../../core/doctor-checker.js";
import { BuildOptions, Web2AppConfig } from "../../types.js";
import { CommandRunner } from "../../utils/command-runner.js";
import { FileSystem } from "../../utils/filesystem.js";
import { Logger } from "../../utils/logger.js";
import { Paths } from "../../utils/paths.js";

export interface GradleBuildResult {
  apkPath: string;
  fileSize: number;
  formattedSize: string;
  durationMs: number;
}

export class GradleRunner {
  /**
   * Run Gradle build to generate native Android APK
   */
  static async build(
    userProjectRoot: string,
    config: Web2AppConfig,
    options: BuildOptions = {}
  ): Promise<GradleBuildResult> {
    const startTime = Date.now();
    const androidDir = Paths.getAndroidProjectDir(userProjectRoot);

    // 1. Setup local.properties
    await this.setupLocalProperties(androidDir);

    // 2. Determine JDK / JAVA_HOME
    const jdk = await DoctorChecker.findJdkPath();
    const env: NodeJS.ProcessEnv = {};
    if (jdk) {
      env.JAVA_HOME = jdk.path;
      env.PATH = `${path.join(jdk.path, "bin")}:${process.env.PATH || ""}`;
      Logger.debug(`Using Java JDK: ${jdk.version} at ${jdk.path}`);
    }

    // 3. Determine Gradle task
    const isRelease = Boolean(options.release);
    const gradleTask = isRelease ? "assembleRelease" : "assembleDebug";
    const isWindows = process.platform === "win32";
    const gradlewBin = path.join(androidDir, isWindows ? "gradlew.bat" : "gradlew");

    if (!(await FileSystem.exists(gradlewBin))) {
      throw new Error(`Gradle wrapper not found at: ${gradlewBin}`);
    }

    Logger.info(`Running Gradle task: ${gradleTask}`);
    const spinner = Logger.spinner("Compiling native Android application...").start();

    const buildArgs = [
      gradleTask,
      "--no-daemon",
      "--stacktrace",
      "-Dorg.gradle.jvmargs=-Xmx2048m -XX:+UseG1GC",
    ];

    try {
      const res = await CommandRunner.run(gradlewBin, buildArgs, {
        cwd: androidDir,
        env,
        verbose: options.verbose,
      });

      if (res.code !== 0) {
        spinner.error({ text: "Gradle compilation failed!" });
        const errorSummary = this.extractGradleError(res.stderr || res.stdout);
        throw new Error(
          `Gradle build failed with exit code ${res.code}.\n\n${errorSummary}`
        );
      }

      spinner.success({ text: "Gradle compilation completed successfully" });
    } catch (err: any) {
      spinner.error({ text: "Gradle compilation failed!" });
      throw err;
    }

    // 4. Locate output APK
    const mode = isRelease ? "release" : "debug";
    const sourceApk = Paths.getGradleApkOutputPath(userProjectRoot, mode);

    if (!(await FileSystem.exists(sourceApk))) {
      throw new Error(
        `Built APK was not found at expected location: ${sourceApk}\n` +
          `Please check Gradle output.`
      );
    }

    // 5. Copy to user dist/android directory
    const distDir = options.out
      ? path.resolve(userProjectRoot, options.out)
      : Paths.getAndroidDistDir(userProjectRoot);

    await FileSystem.ensureDir(distDir);

    const safeAppName = config.appName.toLowerCase().replace(/[^a-z0-9_-]/g, "-");
    const targetApkName = `${safeAppName}-${mode}.apk`;
    const targetApkPath = path.join(distDir, targetApkName);

    await fs.copyFile(sourceApk, targetApkPath);

    const fileSize = await FileSystem.getFileSize(targetApkPath);
    const durationMs = Date.now() - startTime;

    return {
      apkPath: targetApkPath,
      fileSize,
      formattedSize: FileSystem.formatFileSize(fileSize),
      durationMs,
    };
  }

  /**
   * Setup local.properties with sdk.dir
   */
  private static async setupLocalProperties(androidDir: string): Promise<void> {
    const sdkPath = await DoctorChecker.findAndroidSdkPath();
    if (!sdkPath) {
      throw new Error(
        "Android SDK location could not be determined. Please set ANDROID_HOME or install Android SDK."
      );
    }

    const localPropsPath = path.join(androidDir, "local.properties");
    const escapedSdkPath = sdkPath.replace(/\\/g, "/");
    const content = `# Auto-generated by web2app\nsdk.dir=${escapedSdkPath}\n`;

    await FileSystem.writeFile(localPropsPath, content);
    Logger.debug(`Created local.properties with sdk.dir=${escapedSdkPath}`);
  }

  /**
   * Extract meaningful error messages from verbose Gradle output
   */
  private static extractGradleError(output: string): string {
    const lines = output.split("\n");
    const failureLines = lines.filter(
      (l) =>
        l.includes("FAILURE:") ||
        l.includes("* What went wrong:") ||
        l.includes("* Try:") ||
        l.includes("ERROR:") ||
        l.includes("Compilation error")
    );

    if (failureLines.length > 0) {
      return failureLines.join("\n");
    }

    // Fallback to last 15 lines of output
    return lines.slice(-15).join("\n");
  }
}
